### ISSUE TITLE
row with < 19 symbols

### ISSUE THREAD

**Issue by IanaKhitsko** [Zak-Roz/se_methodology#3]
https://github.com/Zak-Roz/se_methodology/blob/70f91e09cbdcbeff78e8a9c4d906531d2ac68b4f/lab1/renju.js#L91C24-L91C29

What will happen if input row includes less than 19 numbers?

**Comment by Zak-Roz** [comment]
<img width="863" alt="image" src="https://github.com/Zak-Roz/se_methodology/assets/56147912/70960d13-21a4-40b2-8a32-6c5363b8628b">

fixed
https://github.com/Zak-Roz/se_methodology/pull/5
