### ISSUE TITLE
Single responsibility principle violation

### ISSUE THREAD

**Issue by dmitri-baklan** [Zak-Roz/se_methodology#6]
From OOP perspective it might be better practice to split the code that responsible for different thing into appropriate classes.
For example this code, may be extracted into separete class `InuptFileReader`.
https://github.com/Zak-Roz/se_methodology/blob/4055115bcf487914f283aa835e138559a8d2b64e/lab1/renju.js#L6C1-L9C2
The same applicable to those two methods `chekcWin()` and `processTestCase()`:
https://github.com/Zak-Roz/se_methodology/blob/4055115bcf487914f283aa835e138559a8d2b64e/lab1/renju.js#L12C1-L73C2

**Comment by Zak-Roz** [comment]
fixed
https://github.com/Zak-Roz/se_methodology/pull/9
